#!bin/bash

GREEN=`tput setaf 2`
reset=`tput sgr0`
message=("$@")

git config --global user.name "Geoffroy Givry"
git config --global user.email "geoff.givry@gmail.com"

echo "# ReadMe" >> README.md
git init
git add -A
git status
git commit -m "initial commit"
git remote add origin "$message"
git remote -v
git push -u origin master


echo "${GREEN}Your git repo $message has been initialized!${reset}"

# how to use it without alias : source goGit "I put my message here". with alias gogit "I put my message here".
